### PR TITLE
Migration

### PR DESCRIPTION
**Pull request by quixley**

### CODE REVIEW

**Comment by gdhillon-pbl** [comment]
Can we avoid moving to swift 5? since it requires Xcode version 10.2 or above. We are using appcenter.ms for build automation which is still on Xcode 10.1.

**Comment by skb1129** [comment]
I'd suggest keeping this for a future release. #108 would be better for a new release right now.

**Comment by quixley** [comment]
No problems. Just keep in mind that it's here.
I ran all the tests, did some manual testing, and everything works as expected.

**Comment by jigs611989** [comment]
@quixley I tried to use you repo but it seems swift version is still 3.0

I updated package.json with the following line.

    "react-native-masked-text": "quixley/react-native-text-input-mask#development"

Deleted /node_module/react-native-text-input-mast

then yarn install

let me know if I missed so,mething.

**Comment by martintreurnicht** [comment]
There has been some major changes since this PR was opened, please have a look at the latest code, if you feel this change is still required, you are welcome to open another PR

**Pull request closed without merging**
